name: Pull request metrics
on:
  pull_request:

jobs:
  artifact-size-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CI_USER_PAT }}

      - name: Configure Gradle
        uses: aws/aws-kotlin-repo-tools/.github/actions/configure-gradle@main

      - name: Build
        shell: bash
        run: |
          ./gradlew build --parallel
          ./gradlew publishAllPublicationsToTestLocalRepository --parallel

      - name: Calculate metrics
        uses: aws/aws-kotlin-repo-tools/.github/actions/artifact-size-metrics/calculate-and-upload@main
        with:
          upload: 'false'
          release_metrics: 'false'

      - name: Configure credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.CI_AWS_ROLE_ARN }}
          aws-region: us-west-2

      - name: Process metrics
        uses: aws/aws-kotlin-repo-tools/.github/actions/artifact-size-metrics/download-and-process@main
        with:
          download: 'false'

permissions:
  id-token: write
  contents: read
